-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 12:08:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema micms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema micms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micms` DEFAULT CHARACTER SET utf8 ;
USE `micms` ;

-- -----------------------------------------------------
-- Table `micms`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`administrador` (
  `adid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `clave` BLOB NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`adid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micms`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`pagina` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(128) NOT NULL,
  `foto` VARCHAR(64) NULL,
  `texto` LONGTEXT NOT NULL,
  `video` VARCHAR(64) NULL,
  `estado` INT NULL,
  `adid` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_pagina_administrador_idx` (`adid` ASC),
  CONSTRAINT `fk_pagina_administrador`
    FOREIGN KEY (`adid`)
    REFERENCES `micms`.`administrador` (`adid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micms`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`articulo` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(128) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `foto` VARCHAR(64) NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  `adid` INT NOT NULL,
  PRIMARY KEY (`aid`),
  INDEX `fk_articulo_administrador1_idx` (`adid` ASC),
  CONSTRAINT `fk_articulo_administrador1`
    FOREIGN KEY (`adid`)
    REFERENCES `micms`.`administrador` (`adid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micms`.`visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`visitante` (
  `vid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `clave` BLOB NOT NULL,
  `telefono` VARCHAR(14) NULL,
  PRIMARY KEY (`vid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micms`.`puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`puntuacion` (
  `puid` INT NOT NULL AUTO_INCREMENT,
  `calificacion` INT NOT NULL,
  `aid` INT NOT NULL,
  `vid` INT NOT NULL,
  PRIMARY KEY (`puid`),
  INDEX `fk_puntuacion_articulo1_idx` (`aid` ASC),
  INDEX `fk_puntuacion_visitante1_idx` (`vid` ASC),
  CONSTRAINT `fk_puntuacion_articulo1`
    FOREIGN KEY (`aid`)
    REFERENCES `micms`.`articulo` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puntuacion_visitante1`
    FOREIGN KEY (`vid`)
    REFERENCES `micms`.`visitante` (`vid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micms`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micms`.`comentario` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(256) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  `vid` INT NOT NULL,
  `aid` INT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fk_comentario_visitante1_idx` (`vid` ASC),
  INDEX `fk_comentario_articulo1_idx` (`aid` ASC),
  CONSTRAINT `fk_comentario_visitante1`
    FOREIGN KEY (`vid`)
    REFERENCES `micms`.`visitante` (`vid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_articulo1`
    FOREIGN KEY (`aid`)
    REFERENCES `micms`.`articulo` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
